aims/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from .views import *

urlpatterns = [
    url(r'login_success/$', login_success, name='login_success'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^management/', include('management.urls')),
    url(r'^data-entry/', include('data_entry.urls', namespace='data-entry')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^project_list/', include('reports.urls', namespace='projects')),
    url(r'^help/', include('help.urls', namespace='help')),
    url(r'^', include('home.urls')),
    url(r'^', include('django.contrib.auth.urls')),
    #url(r'^$', 'aims.views.home', name='home'),


    url(r'^admin/', include(admin.site.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

help/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', HelpPageView.as_view(), name='help'),

]

home/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^$', 'home.views.home', name='home'),
]

reports/urls.py
from django.conf.urls import url
from reports.views import *


urlpatterns = [
    url(r'^$', project_list, name='dashboard'),
    url(r'^export-pdf/$', pdf_gen, name='gen-pdf'),
    url(r'^export-csv/$', csv_gen, name='gen-csv'),
    url(r'^export-xls/$', xls_gen, name='gen-xls'),
    url(r'^sector/export-pdf/$', sector_pdf, name='sec-pdf'),
    url(r'^sector/export-csv/$', sector_csv, name='sec-csv'),
    url(r'^sector/export-xls/$', sector_xls, name='sec-xls'),
    url(r'^sector_report/', sector_report, name='sector-report'),
    url(r'^location_report/', location_report, name='location-report'),
    url(r'^location/export-pdf/$', loc_pdf, name='loc-pdf'),
    url(r'^location/export-csv/$', loc_csv, name='loc-csv'),
    url(r'^location/export-xls/$', loc_xls, name='loc-xls'),
]

help/models.py
from django.db import models

# Create your models here.

help/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

    name.widget.attrs['class'] = 'form-control'
    email.widget.attrs['class'] = 'form-control'
    message.widget.attrs['class'] = 'form-control'

home/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

help/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.views.generic.edit import FormView
from .forms import ContactForm


class HelpPageView(SuccessMessageMixin, FormView):
    """Help Page"""
    template_name = "help/help.html"
    form_class = ContactForm
    success_url = '/'
    success_message = "We have received your email. We will get back to you soon."

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        message = form.cleaned_data['message']

        if name and email and message:
            send_mail(
                "[AIMS Contact Form] New Message from {}".format(name),
                message,
                email,
                ['somali.aims@gmail.com'],
                fail_silently=False)
        return super(HelpPageView, self).form_valid(form)

home/views.py
from django.shortcuts import render_to_response
from django.template.context import RequestContext


def home(request):
    """Home page"""
    return render_to_response("home/homepage.html", locals(), context_instance=RequestContext(request))

templates/home/help.html
{% extends "base.html" %}

{% block title %} Help {% endblock %}

{% block content %}

<div class="row">
  <div class="col-md-12">
    <h3 class="text-center"> Help Page </h3>
  </div>

  {# TODO: Remove placeholder text #}
  {% lorem 3 p %}

  <div class="text-center">
    <h3> Contact Us </h3>
    <p>
      If there's anything we've missed in the Help Module,
      Please contact us below
    </p>
  </div>

      <form method="post" action="/help/" class="form-horizontal">

      {% if form.errors %}

      <div class="has-error form-group">
        <span class="help-block col-md-3 col-md-offset-1">
          Please Fill in All the Fields Correctly
        </span>
      </div>
      {% endif %}

      {% csrf_token %}

      {% for field in form %}

        <div class="form-group">
          <label for="{{ field.id_for_label }}" class="col-md-2 control-label">
            {{ field.label }}
          </label>

          <div class="col-md-10">
          {{ field }}
          </div>
        </div>

      {% endfor %}

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <button type="submit" class="btn btn-default">Send Message</button>
        </div>
      </div>

      </form>

  </div>

</div>

{% endblock %}

templates/home/homepage.html
{% extends "base.html" %}

{% block title %} Home {% endblock %}

{% block header_text%} Menu {% endblock %}

{% block content %}
<div class="row" style="padding-top: 30px;"></div>
<div class="row">
   <div class="col-md-12">

   <p class="text-center">
       Welcome to the Somali Aid Information Management System (AIMS). <br/>
       Here you can view and edit projects and produce reports.  <br/>
       Please use the links below to access the AIMS
   </p>
   </div>
</div>
<hr>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
          <li class="text-center">
          <a href="{% url 'projects:dashboard' %}">Projects</a> - Click here to browse all Projects </li>
          <li class="text-center">
          <a href="{% url 'reports:sector-report' %}">Sector Reports</a> - View a Report for your Sector</li>
          <li class="text-center">
          <a href="{% url 'reports:location-report' %}">Location Reports</a> - View a Report for your Location</li>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">

      {# <li class="text-center"><a href="#">Account Registration </a></li> #}
      <li class="text-center">
      <a href="{% url 'data-entry:dashboard' %}">Add/Edit projects</a> - Click here to manage your Projects</li>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <li class="text-center">
        <a href="{% url 'dashboard' %}">Management</a>  - Click here to manage Sectors, Locations and Organizations</li>
    </div>
</div>
<div class="row" style="padding-bottom: 40px;"></div>
</div>
{% endblock %}