aims/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from .views import *

urlpatterns = [
    url(r'login_success/$', login_success, name='login_success'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^management/', include('management.urls')),
    url(r'^data-entry/', include('data_entry.urls', namespace='data-entry')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^project_list/', include('reports.urls', namespace='projects')),
    url(r'^help/', include('help.urls', namespace='help')),
    url(r'^', include('home.urls')),
    url(r'^', include('django.contrib.auth.urls')),
    #url(r'^$', 'aims.views.home', name='home'),


    url(r'^admin/', include(admin.site.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

management/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .views import *

urlpatterns = [
    url(r'^$', login_required(ManagementDashboard.as_view()), name='dashboard'),
    url(r'^location/create/$', login_required(LocationCreate.as_view()), name='location_add'),
    url(r'^location/update/(?P<pk>[^/]+)/$', login_required(LocationUpdate), name='location_update'),
    url(r'^location/delete/(?P<pk>[^/]+)/$', login_required(LocationDelete.as_view()), name='location_delete'),
    url(r'^organization/create/$', login_required(OrganizationCreate.as_view()), name='organization_add'),
    url(r'^organization/update/(?P<pk>[^/]+)/$', login_required(OrganizationUpdate.as_view()), name='organization_update'),
    url(r'^organization/delete/(?P<pk>[^/]+)/$', login_required(OrganizationDelete.as_view()),
        name='organizations_delete'),
    url(r'^sector/create/$', login_required(SectorCreate.as_view()), name='sector_add'),
    url(r'^sector/update/(?P<pk>[^/]+)/$', login_required(SectorUpdate.as_view()), name='sector_update'),
    url(r'^sector/delete/(?P<pk>[^/]+)/$', login_required(SectorDelete.as_view()),
        name='sector_delete'),
    url(r'^exchange-rate/update/$', login_required(ExchangeRateUpdateView.as_view()), name='rate_update'),
    url(r'^psg/create/$', login_required(PSGCreate.as_view()), name='psg_add'),
    url(r'^psg/update/(?P<pk>[^/]+)/$', login_required(PSGUpdate), name='psg_update'),
    url(r'^psg/delete/(?P<pk>[^/]+)/$', login_required(PSGDelete.as_view()), name='psg_delete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

management/models.py
from django.db import models
from django.conf import settings
import uuid


class UnsavedForeighKey(models.ForeignKey):
    allow_unsaved_instance_assignment = True


class Organization(models.Model):
    """Organizations funding and implementing projects"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200, unique=True)
    short_name = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        db_table = 'organizations'

    def __str__(self):
        if self.short_name:
            return self.short_name
        else:
            return self.name


class Location(models.Model):
    """Regions within Somalia e.g Jubaland"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=250, unique=True)
    lng = models.CharField(max_length=50, blank=True)
    lat = models.CharField(max_length=50, blank=True)

    class Meta:
        db_table = 'locations'

    def __str__(self):
        return self.name


class SubLocation(models.Model):
    """Sub locations under Somalia's regions"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    location = UnsavedForeighKey(Location)
    name = models.CharField(max_length=100, unique=False)
    lng = models.CharField(max_length=50, blank=True)
    lat = models.CharField(max_length=50, blank=True)

    class Meta:
        db_table = 'sublocations'

    def __str__(self):
        return "{0} - {1}".format(self.location.name, self.name)


class Sector(models.Model):
    """Sectors that are receiving funds from the projects"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'sectors'

    def __str__(self):
        return self.name


class Currency(models.Model):
    """Currency abbreviations and their corresponding full names"""
    abbrev = models.CharField(max_length=settings.CURRENCY_ABBREVIATION_LENGTH, unique=True)
    currency = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Currencies"
        db_table = 'currencies'

    def __str__(self):
        return self.abbrev


class ExchangeRate(models.Model):
    """Universal conversion rate from USD to SOM. Set by manager."""
    dateSet = models.DateField(auto_now=True)
    rateToSOM = models.FloatField(default=0.00, blank=True, null=True)

    class Meta:
        db_table = 'exchange_rate_to_usd'

    def __str__(self):
        return str(self.rateToSOM)


class PSG(models.Model):
    """PSGs for projects"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        db_table = 'psg'

    def __str__(self):
        return self.name


class SubPSG(models.Model):
    """SubPSGs for projects"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    psg = UnsavedForeighKey(PSG)
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        db_table = 'sub_psg'
        verbose_name_plural = 'sub-psgs'

    def __str__(self):
        return "{0} - {1}".format(self.psg, self.name)

management/views.py
from django.shortcuts import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from management.models import Location, Organization, Sector, ExchangeRate, SubLocation, PSG, SubPSG
from django.views.generic import ListView
from .forms import LocationForm, SubLocationFormset, OrganizationForm, BaseOrganizationFormSet, ExchangeRateForm, \
    BaseSectorFormSet, SectorForm, BaseSubLocationFormset, BaseSubPSGFormset, SubPSGFormset, PSGForm, SubPSGForm
from django.core.urlresolvers import reverse_lazy
from django.forms.models import modelformset_factory
from django.forms.models import inlineformset_factory
from braces.views import GroupRequiredMixin
from django.template.context import RequestContext
from django.shortcuts import render_to_response


class ManagementDashboard(GroupRequiredMixin, ListView):
    model = Organization
    template_name = "management/index.html"
    queryset = Location.objects.all()
    group_required = [u"admin", "manager"]

    def get_context_data(self, **kwargs):
        context = super(ManagementDashboard, self).get_context_data(**kwargs)
        context['organizations'] = Organization.objects.all()
        context['sectors'] = Sector.objects.all()
        context['psgs'] = PSG.objects.all()
        try:
            context['exchange_rate'] = ExchangeRate.objects.get()
        except ExchangeRate.DoesNotExist:
            pass
        return context

    def dispatch(self, *args, **kwargs):
        return super(ManagementDashboard, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Location.objects.all()


class OrganizationCreate(GroupRequiredMixin, CreateView):
    model = Organization
    form_class = OrganizationForm
    group_required = [u"admin", "manager"]

    def get_context_data(self, **kwargs):
        context = super(OrganizationCreate, self).get_context_data(**kwargs)
        organizationFormset = modelformset_factory(Organization, form=OrganizationForm, fields=('name', 'short_name'),
                                                   formset=BaseOrganizationFormSet)
        context['formset'] = organizationFormset()
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        sett = modelformset_factory(Organization, form=OrganizationForm, fields=('name', 'short_name'), extra=1,
                                    formset=BaseOrganizationFormSet)
        formset = sett(request.POST)
        if formset.is_valid():
            return self.form_valid(formset)
        else:
            return self.form_invalid(formset)

    def form_valid(self, formset):
        formset.save()
        return HttpResponseRedirect(reverse('dashboard'))

    def form_invalid(self, formset):
        return self.render_to_response(self.get_context_data(formset=formset))


class OrganizationUpdate(GroupRequiredMixin, UpdateView):
    model = Organization
    form_class = OrganizationForm
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('dashboard')
    group_required = [u"admin", "manager"]

    def get_object(self, queryset=None):
        obj = Organization.objects.get(id=self.kwargs['pk'])
        return obj


class OrganizationDelete(GroupRequiredMixin, DeleteView):
    model = Organization
    success_url = reverse_lazy('dashboard')
    group_required = [u"admin", "manager"]


class LocationCreate(GroupRequiredMixin, CreateView):
    model = Location
    form_class = LocationForm
    group_required = [u"admin", "manager"]

    def get_context_data(self, **kwargs):
        context = super(LocationCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = SubLocationFormset(self.request.POST)
        else:
            context['formset'] = SubLocationFormset()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            saves = formset.save(commit=False)
            for save in saves:
                save.location = self.object
                save.save()
            # formset.save()
            return HttpResponseRedirect(reverse('dashboard'))  # assuming your model has ``get_absolute_url`` defined.
        else:
            return self.render_to_response(self.get_context_data(form=form))


def LocationUpdate(request, pk=False):
    formset = inlineformset_factory(Location, SubLocation, fields=('name',), extra=1)
    if pk:
        location = Location.objects.get(pk=pk)
    else:
        location = Location()
    if request.POST:
        form = LocationForm(request.POST, request.FILES, instance=location)
        formset = formset(request.POST, instance=location)
        if formset.is_valid() and form.is_valid():
            form.save()
            formset.save()
            return HttpResponseRedirect(reverse('dashboard'))
    else:
        form = LocationForm(instance=location)
        formset = formset(instance=location)
    return render_to_response('management/location_update_form.html', locals(),
                              context_instance=RequestContext(request))


class LocationDelete(GroupRequiredMixin, DeleteView):
    model = Location
    success_url = reverse_lazy('dashboard')
    group_required = [u"admin", "manager"]


class ExchangeRateUpdateView(GroupRequiredMixin, UpdateView):
    form_class = ExchangeRateForm
    success_url = reverse_lazy('dashboard')
    group_required = [u"admin", "manager"]

    def get_object(self, queryset=None):
        obj, created = ExchangeRate.objects.get_or_create()

        return obj


class SectorCreate(GroupRequiredMixin, CreateView):
    model = Sector
    form_class = SectorForm
    group_required = [u"admin", "manager"]

    def get_context_data(self, **kwargs):
        context = super(SectorCreate, self).get_context_data(**kwargs)
        sectorFormset = modelformset_factory(Sector, form=SectorForm, fields=('name', 'description'),
                                             formset=BaseSectorFormSet)
        context['formset'] = sectorFormset()
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        set = modelformset_factory(Sector, form=SectorForm, fields=('name', 'description'), extra=1,
                                   formset=BaseSectorFormSet)
        formset = set(request.POST)
        if formset.is_valid():
            return self.form_valid(formset)
        else:
            return self.form_invalid(formset)

    def form_valid(self, formset):
        formset.save()
        return HttpResponseRedirect(reverse('dashboard'))

    def form_invalid(self, formset):
        return self.render_to_response(self.get_context_data(formset=formset))


class SectorUpdate(GroupRequiredMixin, UpdateView):
    model = Sector
    form_class = SectorForm
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('dashboard')
    group_required = [u"admin", "manager"]

    def get_object(self, queryset=None):
        obj = Sector.objects.get(id=self.kwargs['pk'])
        return obj


class SectorDelete(GroupRequiredMixin, DeleteView):
    model = Sector
    success_url = reverse_lazy('dashboard')
    group_required = [u"admin", "manager"]


class PSGCreate(GroupRequiredMixin, CreateView):
    model = PSG
    form_class = PSGForm
    group_required = [u"admin", "manager"]
    template_name = "management/psg_form.html"
    formset_class = SubPSGFormset

    def get_context_data(self, **kwargs):
        context = super(PSGCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = SubPSGFormset(self.request.POST)
        else:
            context['formset'] = SubPSGFormset()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid() and form.is_valid():
            self.object = form.save()
            form.save()
            saves = formset.save(commit=False)
            for save in saves:
                save.psg = self.object
                save.save()
            return HttpResponseRedirect(reverse('dashboard'))
        else:
            return self.render_to_response(self.get_context_data(form=form))


def PSGUpdate(request, pk=False):
    formset = inlineformset_factory(PSG, SubPSG, fields=('name',), extra=1)
    if pk:
        psg = PSG.objects.get(pk=pk)
    else:
        psg = PSG()
    if request.POST:
        form = PSGForm(request.POST, request.FILES, instance=psg)
        formset = formset(request.POST, instance=psg)
        if formset.is_valid() and form.is_valid():
            form.save()
            formset.save()
            return HttpResponseRedirect(reverse('dashboard'))
    else:
        form = PSGForm(instance=psg)
        formset = formset(instance=psg)
    return render_to_response('management/psg_update_form.html', locals(), context_instance=RequestContext(request))


class PSGDelete(GroupRequiredMixin, DeleteView):
    model = PSG
    success_url = reverse_lazy('dashboard')
    group_required = [u"admin", "manager"]

templates/management/exchangerate_form.html
{% extends "base.html" %}

{% block content %}
<div class="container">

<div class="row" style="padding-top: 40px"></div>
<div class="row">
<div class="col-md-4"></div>
<div class="col-md-4">
<form id="myForm" method="post" action="">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
            <div class="form-group">
                <label for="rateToSOM">USD to SOM rate</label>
                {{ form.rateToSOM }}
            </div>
            <div class="form-group">
            <button type="submit" class="btn btn-default btn-large">Update exchange rate</button>
            &emsp; &ensp;
            <a href="{% url 'dashboard' %}">Go back</a>
            </div>
       </form>
</div>
<div class="col-md-4"></div>
</div>
</div>
{% endblock %}

templates/management/index.html
{% extends "base.html" %}

{% block title %} Management {% endblock %}

{% block header_text%} Management {% endblock %}

{% block content %}
<div class="container">

<div class="row" style="padding-top: 30px;"></div>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <div class="row">
            {% if exchange_rate %}
            <h4 style="text-align: center;">Exhange Rate(USD to SOM): {{ exchange_rate.rateToSOM }} &nbsp;
                <a href="{% url 'rate_update' %}">Edit</a>
            </h4>
            {% else %}
                <h4 style="text-align: center;"><a href="{% url 'rate_update' %}">Set exchange rate</a></h4>
            {% endif %}
        </div>
    </div>
    <div class="col-md-4"></div>
</div>
<div class="row" style="padding-top: 20px;"></div>
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
{% if object_list %}
    <table class="table table-bordered table-condensed">
    <tr>
        <th>Locations</th>
    </tr>
    {% for location in object_list|slice:":" %}
    <tr>
        <td>
        <a href="{% url 'location_update' location.id %}">{{ location.name }}</a>
        </td>
    </tr>
    {% endfor %}
    </table>
    <p><a href="#">View all locations</a></p>
    <span><a href="{% url 'location_add' %}">Add location</a></span>
{% else %}
    <p>No locations available</p>
    <p><a href="{% url 'location_add' %}">Add location</a></p>
{% endif %}
</div>
</div>
<div class="col-md-2"></div>
<div class="row" style="padding-top: 30px;"></div>
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
    {% if organizations %}
        <table class="table table-bordered table-condensed">
            <tr>
                <th>Organizations</th>
            </tr>
            {% for organization in organizations|slice:":" %}
                <tr>
                    <td>
                    <a href="{% url 'organization_update' organization.id %}">{{ organization.name }}</a>
                    </td>
                </tr>
            {% endfor %}

        </table>
        <p><a href="#">View all organizations</a></p>
        <span><a href="{% url 'organization_add' %}">Add organization</a></span>
    {% else %}
        <p>No organizations available</p>
        <p><a href="{% url 'organization_add' %}">Add organization</a></p>
    {% endif %}
</div>
<div class="col-md-2"></div>
</div>
<div class="row" style="padding-top: 30px;"></div>
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
    {% if sectors %}
        <table class="table table-bordered table-condensed">
            <tr>
                <th>Sectors</th>
            </tr>
    {% for sector in sectors %}
    <tr>
        <td>
        <a href="{% url 'sector_update' sector.id %}">{{ sector.name }}</a>
        </td>
    </tr>
    {% endfor %}

</table>
<p><a href="#">View all sectors</a></p>
<span><a href="{% url 'sector_add' %}">Add sector</a></span>
{% else %}
    <p>No sectors available</p>
    <p><a href="{% url 'sector_add' %}">Add sector</a></p>
{% endif %}
</div>
<div class="col-md-2"></div>
</div>
<div class="row" style="padding-top: 30px;"></div>
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
    {% if psgs %}
        <table class="table table-bordered table-condensed">
            <tr>
                <th>PSGs</th>
            </tr>
    {% for psg in psgs %}
    <tr>
        <td>
        <a href="{% url 'psg_update' psg.id %}">{{ psg.name }}</a>
        </td>
    </tr>
    {% endfor %}

</table>
<p><a href="#">View all PSGs</a></p>
<span><a href="{% url 'psg_add' %}">Add PSG</a></span>
{% else %}
    <p>No psgs available</p>
    <p><a href="{% url 'psg_add' %}">Add PSG</a></p>
{% endif %}
</div>
<div class="col-md-2"></div>
</div>
</div>
{% endblock %}

templates/management/location_confirm_delete.html
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
    &emsp; &ensp;
    <a href="{% url 'location_update' object.id %}">Go back</a>
</form>

{% endblock %}

templates/management/location_form.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} Add Location {% endblock %}

{% block header_text%} Add Location {% endblock %}

{% block content %}
<div class="container">

<div class="row" style="padding-top: 40px"></div>

<div class="row">
<div class="col-md-3"></div>
<div class="col-md-6">
<h3>Add Location</h3>
<form id="myForm" class="form" method="post" action="">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
            <div class="form-group">
                {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
                {{ form.non_field_errors }}
                {{ form.name.errors }}
            </div>
            <div class="form-group">
                <label for="name">Location name</label>
                {{ form.name }}
            </div>
           <legend>
                Sublocations
            </legend>
           <table class="table" border="0" cellpadding="0" cellspacing="0">
               <tbody id="location">
                   {% for form in formset.forms %}
                   {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
                   <tr>
                      <td>{{ form.name }}</td>
                   </tr>
                   {% endfor %}
               </tbody>
           </table>
           {{ formset.management_form }}
            <button class="btn btn-default btn-large" type="submit">Add Location</button>
            &emsp; &ensp;
            <a href="{% url 'dashboard' %}">Go back</a>
       </form>
</div>
<div class="col-md-3"></div>
</div>
</div>
{% endblock %}

templates/management/location_update_form.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} Update Location {% endblock %}

{% block header_text%} Update Location {% endblock %}

{% block content %}
<div class="container">

<div class="row" style="padding-top: 40px"></div>

<div class="row">
<div class="col-md-3"></div>
<div class="col-md-6">
<h3>Update Location</h3>
<form id="myForm" class="form" method="post" action="">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
            <div class="form-group">
                {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
                {{ form.non_field_errors }}
                {{ form.name.errors }}
            </div>
            <div class="form-group">
                <label for="name">Location name</label>
                {{ form.name }}
            </div>
           <legend>
                Sublocations
            </legend>
           <table class="table" border="0" cellpadding="0" cellspacing="0">
               <tbody id="location">
                   {% for form in formset.forms %}
                   {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
                   <tr>
                      <td>{{ form.name }}</td>
                   </tr>
                   {% endfor %}
               </tbody>
           </table>
           {{ formset.management_form }}
            <button class="btn btn-default btn-large" type="submit">Update Location</button>
            &emsp; &ensp;
            <a href="{% url 'dashboard' %}">Go back</a>
       </form>
</div>
<div class="col-md-3"></div>
</div>
</div>
{% endblock %}

templates/management/organization_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
    &emsp; &ensp;
    <a href="{% url 'organization_update' object.id %}">Go back</a>
    </form>

{% endblock %}

templates/management/organization_form.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} Create Organization {% endblock %}

{% block header_text%} Add Organization {% endblock %}

{% block content %}

<div class="container">

<div class="row" style="padding-top: 40px"></div>

<div class="row">
<div class="col-md-3"></div>
<div class="col-md-6">
<h3>Add Organization</h3>
<form id="myForm" class="form" method="post" action="">
            {% csrf_token %}
           <table class="table table-bordered" border="0" cellpadding="0" cellspacing="0">
               <tbody id="organization">
                   {% for form in formset.forms %}
                   {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
                   <tr>
                      <td>
                           <label for="id_name">Name</label>
                          {{ form.name }}
                      </td>
                   </tr>
                   <tr>
                      <td>
                          <label for="id_short_name">Short Name</label>
                          {{ form.short_name }}
                      </td>
                   </tr>
                   {% endfor %}
               </tbody>
           </table>
           {{ formset.management_form }}
           <button class="btn btn-default btn-large" type="submit">Add Organizations(s)</button>
           &emsp; &ensp;
            <a href="{% url 'dashboard' %}">Go back</a>
       </form>
</div>
<div class="col-md-3"></div>
</div>
</div>
{% endblock %}

templates/management/organization_update_form.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} Update Organization {% endblock %}

{% block header_text%} Update Organization {% endblock %}

{% block content %}
<div class="container">
<div class="row" style="padding-top: 30px"></div>
<div class="row">
<div class="col-md-3"></div>
    <div class="col-md-6">
        <h3>Update organization</h3>
<form id="myForm" class="form" method="post" action="">
            {% csrf_token %}

           {{ form }}
            <br>
           <button type="submit" class="btn btn-default btn-large">Update organization</button>
            &emsp; &ensp;
            <a href="{% url 'dashboard' %}">Go back</a>
       </form>
        </div>
    <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

templates/management/psg_confirm_delete.html
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
    &emsp; &ensp;
    <a href="{% url 'psg_update' object.id %}">Go back</a>
</form>

{% endblock %}

templates/management/psg_form.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} Add PSG {% endblock %}

{% block header_text%} Add PSG {% endblock %}

{% block content %}
<div class="container">

<div class="row" style="padding-top: 40px"></div>

<div class="row">
<div class="col-md-3"></div>
<div class="col-md-6">
<h3>Add PSG</h3>
<form id="myForm" class="form" method="post" action="">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
            <div class="form-group">
                {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
                {{ form.non_field_errors }}
                {{ form.name.errors }}
            </div>
            <div class="form-group">
                <label for="name">PSG name</label>
                {{ form.name }}
                <label for="description">Description</label>
                {{ form.description }}
            </div>
           <legend>
                Sub-PSGs
            </legend>
           <table class="table" border="0" cellpadding="0" cellspacing="0">
               <tbody id="location">
                   {% for form in formset %}
                   {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
                   <tr>
                      <td>{{ form.name }}</td>
                   </tr>
                   {% endfor %}
               </tbody>
           </table>
           {{ formset.management_form }}
            <button class="btn btn-default btn-large" type="submit">Add PSG</button>
            &emsp; &ensp;
            <a href="{% url 'dashboard' %}">Go back</a>
       </form>
</div>
<div class="col-md-3"></div>
</div>
</div>
{% endblock %}

templates/management/sector_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
    &emsp; &ensp;
    <a href="{% url 'sector_update' object.id %}">Go back</a>
</form>

{% endblock %}

templates/management/sector_update_form.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} Update Sector {% endblock %}

{% block header_text%} Update Sector {% endblock %}

{% block content %}
<div class="container">

<div class="row" style="padding-top: 30px"></div>
<div class="row">
<div class="col-md-3"></div>
    <div class="col-md-6">
        <h3>Update Sector</h3>
<form id="myForm" class="form" method="post" action="">
            {% csrf_token %}

           {{ form }}
            <br>
           <button type="submit" class="btn btn-default btn-large">Update sector</button>
            &emsp; &ensp;
            <a href="{% url 'dashboard' %}">Go back</a>
       </form>
        </div>
    <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}