aims/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from .views import *

urlpatterns = [
    url(r'login_success/$', login_success, name='login_success'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^management/', include('management.urls')),
    url(r'^data-entry/', include('data_entry.urls', namespace='data-entry')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^project_list/', include('reports.urls', namespace='projects')),
    url(r'^help/', include('help.urls', namespace='help')),
    url(r'^', include('home.urls')),
    url(r'^', include('django.contrib.auth.urls')),
    #url(r'^$', 'aims.views.home', name='home'),


    url(r'^admin/', include(admin.site.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

data_entry/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    # url(r'^$', login_required(ProjectListView.as_view()), name='dashboard'),
    url(r'^$', login_required(ProjectListView), name='dashboard'),
    url(r'^project/create/$', login_required(ProjectCreateView.as_view()), name='project_add'),
    url(r'^project/update/(?P<pk>[^/]+)/$', login_required(ProjectUpdateView.as_view()), name='project_update'),
    url(r'^project/details/(?P<pk>[^/]+)/$', ProjectDetailView.as_view(), name='project_details'),
    url(r'^project/export/(?P<pk>[^/]+)/$', project_export, name='project_export'),
    url(r'^download/(?P<pk>[^/]+)/$', download_handler, name='download'),
    url(r'^project/delete/(?P<pk>[^/]+)/$', login_required(ProjectDelete.as_view()),
        name='project_delete'),
    #url(r'^sublocations/(?P<locationID>[^/]+)/', getSublocations, name='sublocations'),
    url(r'^sublocations/$', ajaxSublocations, name='ajax_sublocations'),
    url(r'^subpsgs/$', ajaxSubPSGs, name='ajax_subpsgs'),
]

help/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', HelpPageView.as_view(), name='help'),

]

reports/urls.py
from django.conf.urls import url
from reports.views import *


urlpatterns = [
    url(r'^$', project_list, name='dashboard'),
    url(r'^export-pdf/$', pdf_gen, name='gen-pdf'),
    url(r'^export-csv/$', csv_gen, name='gen-csv'),
    url(r'^export-xls/$', xls_gen, name='gen-xls'),
    url(r'^sector/export-pdf/$', sector_pdf, name='sec-pdf'),
    url(r'^sector/export-csv/$', sector_csv, name='sec-csv'),
    url(r'^sector/export-xls/$', sector_xls, name='sec-xls'),
    url(r'^sector_report/', sector_report, name='sector-report'),
    url(r'^location_report/', location_report, name='location-report'),
    url(r'^location/export-pdf/$', loc_pdf, name='loc-pdf'),
    url(r'^location/export-csv/$', loc_csv, name='loc-csv'),
    url(r'^location/export-xls/$', loc_xls, name='loc-xls'),
]

data_entry/models.py
from django.db import models
from management.models import Organization, Currency, Location, Sector, SubLocation, SubPSG, PSG
import datetime
from datetime import timedelta
from calendar import monthrange
import uuid
from django.conf import settings


class UnsavedForeighKey(models.ForeignKey):
    allow_unsaved_instance_assignment = True


class Project(models.Model):
    """Projects receiving AID"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    name = models.TextField()
    description = models.TextField()
    lastModified = models.DateField(auto_now=True, blank=True, null=True)
    startDate = models.DateField(blank=True, null=True)
    endDate = models.DateField(blank=True, null=True)
    funders = models.ManyToManyField(Organization, related_name="funders")
    implementers = models.ManyToManyField(Organization, related_name="implementers")
    value = models.FloatField()
    currency = models.ForeignKey(Currency)
    rateToUSD = models.DecimalField(max_digits=6, decimal_places=2)
    active = models.BooleanField(default=True, blank=True)
    ocha_fts_reported = models.NullBooleanField(blank=True, null=True, choices=settings.BOOLEAN_CHOICES)
    sdrf_ssa = models.CharField(max_length=100, blank=True, null=True, choices=settings.SDRF_SSA_CHOICES)
    funding_instrument = models.CharField(max_length=100, blank=True, null=True, choices=settings.FUNDING_INSTRUMENTS)
    funding_channel = models.CharField(max_length=20, blank=True, null=True, choices=settings.FUNDING_CHANNELS)
    gender = models.CharField(max_length=20, blank=True, null=True, choices=settings.MULTIFIELD_CHOICES)
    capacity_building = models.CharField(max_length=20, blank=True, null=True, choices=settings.MULTIFIELD_CHOICES)
    stabilization = models.CharField(max_length=20, blank=True, null=True, choices=settings.MULTIFIELD_CHOICES)
    conflict_sensitivity_analysis = models.CharField(max_length=100, blank=True, null=True,
                                                     choices=settings.SENSITIVITY_ANALYSIS_CHOICES)
    conflict_sensitivity_monitoring = models.NullBooleanField(blank=True, null=True, choices=settings.BOOLEAN_CHOICES)

    class Meta:
        db_table = 'project'

    def __str__(self):
        return self.name

    def save(self):
        if datetime.date.today() > self.endDate.date():
            self.active = False
        else:
            pass
        super(Project, self).save()

    @property
    def duration(self):
        delta = 0
        while True:
            mdays = monthrange(self.startDate.year, self.startDate.month)[1]
            self.startDate += timedelta(days=mdays)
            if self.startDate <= self.endDate:
                delta += 1
            else:
                break
        out = "{0} months".format(delta)
        return out

    @property
    def percentage_spent(self):
        spending = Spending.objects.get(project=self).spendingToDate
        try:
            percentage = (spending / self.value) * 100
        except ZeroDivisionError:
            percentage = 0
        out = "{0:5.2f} %".format(percentage)
        return out

    @property
    def locations(self):
        l = LocationAllocation.objects.filter(project=self).values_list('location')
        f = Location.objects.filter(id__in=l).values_list('name')
        location_list = [' '.join(item) for item in f]
        return location_list

    @property
    def sublocations(self):
        l = LocationAllocation.objects.filter(project=self).values_list('sublocations')
        f = SubLocation.objects.filter(id__in=l).values_list('name')
        sublocation_list = [' '.join(item) for item in f]
        return sublocation_list

    @property
    def sectors(self):
        l = SectorAllocation.objects.filter(project=self).values_list('sector')
        f = Sector.objects.filter(id__in=l).values_list('name')
        sector_list = [' '.join(item) for item in f]
        return sector_list


class Spending(models.Model):
    """How a project's value has and is intended to been spent"""
    project = models.OneToOneField(Project)
    spendingToDate = models.FloatField(help_text="Total amount of aid spent up to date", blank=True, null=True)
    lastYearSpending = models.FloatField(help_text="Total amount of aid spent last year", blank=True, null=True)
    thisYearSpending = models.FloatField(help_text="Amount expected to be spent this year", blank=True)
    nextYearSpending = models.FloatField(help_text="Total amount of aid anticipated to be spent next year", blank=True,
                                         null=True)

    class Meta:
        db_table = 'project_spending'

    def __str__(self):
        return self.project.name


class Contact(models.Model):
    """Person who knows more about the Project"""
    project = models.OneToOneField(Project)
    name = models.CharField(max_length=100)
    organization = models.CharField(max_length=100, blank=True, null=True)
    number = models.CharField(max_length=50)
    email = models.EmailField()

    class Meta:
        db_table = 'project_contacts'

    def __str__(self):
        return self.name


class Document(models.Model):
    """Documents relevant to a project"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = UnsavedForeighKey(Project)
    file = models.FileField(upload_to=settings.DOCUMENT_UPLOAD_DIR, blank=True, null=True)
    name = models.CharField(max_length=150, blank=True, null=True)
    link_to_document_website = models.URLField(blank=True, null=True)

    class Meta:
        db_table = 'project_documents'

    def __str__(self):
        return "{0}".format(self.name)


class SectorAllocation(models.Model):
    """Amount of project's value spent in various sectors"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = UnsavedForeighKey(Project)
    sector = models.ForeignKey(Sector)
    allocatedPercentage = models.DecimalField(max_digits=4, decimal_places=1)

    class Meta:
        db_table = 'sector_allocations'

    def __str__(self):
        return "{0} - {1} - {2}".format(self.project.name, self.sector.name, self.allocatedPercentage)

    @property
    def percentage(self):
        precentage = "{0:5.2f} %".format(self.allocatedPercentage)
        return precentage


class LocationAllocation(models.Model):
    """Percentage of project's value spent in various locations"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = UnsavedForeighKey(Project)
    location = models.ForeignKey(Location)
    sublocations = models.ManyToManyField(SubLocation)
    allocatedPercentage = models.DecimalField(max_digits=4, decimal_places=1)

    class Meta:
        db_table = 'location_allocations'

    def __str__(self):
        return "{0} - {1} - {2}".format(self.project.name, self.location.name, self.allocatedPercentage)

    @property
    def percentage(self):
        precentage = "{0:5.2f} %".format(self.allocatedPercentage)
        return precentage


class UserOrganization(models.Model):
    """Organizations missing in organization list but involved in projects. User defined"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    project = UnsavedForeighKey(Project)
    name = models.CharField(max_length=200, help_text="Organization involved in project but not in existing list",
                            unique=True)
    role = models.CharField(max_length=12, choices=(('Funder', 'Funder'), ('Implementer', 'Implementer')),
                            help_text="Role of organization in project")

    class Meta:
        db_table = 'user_organisations'

    def __str__(self):
        return self.name


class SubPSGAllocation(models.Model):
    """Percentage of project's value allocated to various subPSGs"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = UnsavedForeighKey(Project)
    psg = models.ForeignKey(PSG)
    subpsg = models.ForeignKey(SubPSG)
    allocatedPercentage = models.DecimalField(max_digits=4, decimal_places=1)

    class Meta:
        db_table = 'subpsg_allocations'

    def __str__(self):
        return "{0} - {1} - {2}".format(self.project.name, self.subpsg.name, self.allocatedPercentage)

    @property
    def percentage(self):
        precentage = "{0:5.2f} %".format(self.allocatedPercentage)
        return precentage

reports/models.py
from django.db import models

# Create your models here.

reports/forms.py
from django import forms
from management.models import Location, Sector, SubLocation
#from data_entry.models import LocationAllocation


def get_locations():
    return [[x.id, x.name] for x in Location.objects.all()]


def get_sectors():
    return [[x.id, x.name] for x in Sector.objects.all()]

# SUBLOCATIONS = [[x.id, x.name] for x in LocationAllocation.sublocations.all()]


def get_sublocations():
    return [[x.id, x.name] for x in SubLocation.objects.all()]


class LocationForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(LocationForm, self).__init__(*args, **kwargs)
        self.fields['locations'] = forms.MultipleChoiceField(choices=get_locations(), label="")


class SectorForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(SectorForm, self).__init__(*args, **kwargs)
        self.fields['sectors'] = forms.MultipleChoiceField(choices=get_sectors(), label="")


class SublocationForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(SublocationForm, self).__init__(*args, **kwargs)
        self.fields['sublocations'] = forms.MultipleChoiceField(choices=get_sublocations(), label="")


class SectorReportForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(SectorReportForm, self).__init__(*args, **kwargs)
        self.fields['sector'] = forms.ChoiceField(choices=[('', '----------'), ] + get_sectors(), label='Sector',
                                                  widget=forms.Select(attrs={'onChange': "this.form.submit();"}))


class LocationReportForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(LocationReportForm, self).__init__(*args, **kwargs)
        self.fields['location'] = forms.ChoiceField(choices=[('', '----------'), ] + get_locations(), label="Location",
                                 widget=forms.Select(attrs={'onChange': "this.form.submit();"}))

templates/reports/index.html
{% load staticfiles %}
{% load humanize %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title> {% block title %} Project List {% endblock %} | Somalia AIMS </title>
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>

    {% load bootstrap3 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" />

    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/bootstrap-multiselect.css' %}" type="text/css"/>
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css">
    <script type="text/javascript" src="{% static 'js/bootstrap-multiselect.js' %}"></script>
    <script src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
    

    <style>
        .container-full {
            margin: 0 auto;
            width: 95%;
        }
        .title-projects{
            font-weight: normal;
            color: #555555;
        }
        .btns{
            margin-top: 10px;
        }
        .nomargin {
            margin: 0px important!;
        }
        .some-space {
            margin-bottom: 15px;
        }
        input[type="search"] {
            display: inline-block;
            width: 60%;
            height: 34px;
            padding: 6px 12px;
            font-size: 14px;
            line-height: 1.428571429;
            color: #555555;
            background-color: #ffffff;
            border: 1px solid #cccccc;
            border-radius: 4px;
            -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
                      box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
            -webkit-transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
                      transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
        }
        input[type="search"]:focus {
              border-color: #66afe9;
              outline: 0;
              -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(102, 175, 233, 0.6);
                      box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(102, 175, 233, 0.6);
        }
        hr {
            margin: 0px;
            padding: 0px;
        }
        .btn {
            margin-top:0px;
        }
    </style>
    <script type="text/javascript">
    $(function() {
        $('.add-row').click(function(){
            $('select').multiselect({
                disableIfEmpty: true,
                maxHeight: 200,
                buttonWidth: '140px',
                enableFiltering: true
            });
        });
    });
    $(function() {
        $('select').multiselect({
                disableIfEmpty: true,
                maxHeight: 200,
                buttonWidth: '140px',
                enableFiltering: true
            });
    });
    </script> 
    <script>
        $(document).ready(function(){
            $('#id_startDate').datepicker();
            $('#id_startDate').on('changeDate', function(ev){
                $(this).datepicker('hide');
            });
            $('#id_endDate').datepicker();
            $('#id_endDate').on('changeDate', function(ev){
                $(this).datepicker('hide');
            });


            //id_decription toggle
             $('#id_description').click(function () {
                if ($("#id_description").is(':checked'))
                    $('td p').show();  // checked
                else
                    $('td p').hide();
            });

            //Create dataTable
            $('#myTable').dataTable();

            $('option', $('#id_funders__icontains')).each(function (element) {
                $(this).removeAttr('selected').prop('selected', false);
            });

            $('option', $('#id_implementers__icontains')).each(function (element) {
                $(this).removeAttr('selected').prop('selected', false);
            });

            $('#id_funders__icontains').multiselect('refresh');
            $('#id_implementers__icontains').multiselect('refresh');

            $('#reset').on('click', function () {
                $('option', $('#id_funders__icontains')).each(function (element) {
                    $(this).removeAttr('selected').prop('selected', false);
                });
                $('option', $('#id_implementers__icontains')).each(function (element) {
                    $(this).removeAttr('selected').prop('selected', false);
                });
                $('#id_funders__icontains').multiselect('refresh');
                $('#id_implementers__icontains').multiselect('refresh');
            });
        });
    </script>
</head>
<body>
<div class="container-full">

    <div class="container-fluid" style="border:1px solid #c0c0c0; margin-top:20px;"> <!-- Start of header -->
            <div class="row"><!-- Start of row -->
                
                <div class="col-md-4">
                          <h2 class="text-center">Somali AIMS: <span class="title-projects">Projects</span> <h2>
                </div>

                <div class="col-md-4">
                </div>

                <div class="col-md-4" style="padding-top:10px;padding-right-10px;">
                        <div class="text-right">
                            <span>
                                <a href="{% url 'home' %}">Menu </a>
                            </span>
                            {% if user.is_authenticated %}
                            <span>
                                <a href="{% url 'logout' %}">| Logout </a>
                            </span>
                            {% else %}
                            <span>
                                <a href="{% url 'login' %}">| Login </a>
                            </span>
                            {% endif %}

                            <span>
                                <a href="{% url 'help:help' %}">| Help</a>
                            </span>
                        </div>
                        
                        <div class="text-right">
                            <p></p>
                            <p>{% if exporters %}Export: <a href="{{ pdf_url }}">pdf</a> | <a href="
                            {{ csv_url }}">csv</a> | <a href="
                            {{ xls_url }}">xls</a>{% endif %}</p>
                        </div>
                </div>

            </div><!-- End of row -->
    </div><!-- End of header -->

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                <span class="text-success">{{ message }} </span>
            </li>
            {% endfor %}
        </ul>
    {% endif %}


<div class="container-fluid" style="font-size: 11px;line-height: 1;">
<div class="row" style="padding-top: 40px;"></div>

<form action="" method="get"><!--start of form-->
    <div class="row nomargin"><!--start of row-->

        <div class="col-md-4">
            <div class="row">
                <div class="col-md-4">
                    <label for="locations">Locations</label> <br />
                    {{ loc_form }}
                </div>
                <div class="col-md-4">
                    <label for="sublocations">Sublocations</label> <br />
                    {{ sub_form }}
                </div>
                <div class="col-md-4">
                    <label for="sectirs">Sectors</label> <br />
                    {{ sec_form }}
                </div>
            </div>    
        </div>

        <div class="col-md-2">
            <div class="col-md-12">
                <label for="funders__icontains">Funders</label>
                <div class="form-group">
                    {{ filtered.form.funders__icontains }}
                </div>
                <label for="implementers__icontains">Implementers</label>
                <div class="form-group">
                    {{ filtered.form.implementers__icontains }}
                </div>
            </div>

        </div>
        
        <div class="col-md-3">
                <label for="projectLessValue">Value Of Project Less Then</label>
                <input class="form-control some-space" id="id_value__lt" name="value__lt" step="any" type="number"
                       placeholder="value less than">
                <label for="projectGreatValue">Value Of Project Greater Then</label>
                <input class="form-control some-space" id="id_value__gt" name="value__gt" step="any" type="number"
                       placeholder="value greater than">
                <label for="project_name">Project Name</label>
                <input class="form-control some-space" id="id_name__icontains" name="name__icontains" type="text" placeholder="project name">
        </div>
        
        <div class="col-md-3">
                <label for="startDate">Project Start Date</label>
                <input class="form-control some-space" id="id_startDate" name="startDate" type="text" placeholder="start date">
                <label for="endDate">Project End Date</label>
                <input class="form-control some-space" id="id_endDate" name="endDate" type="text" placeholder="end date">
                <br />
                <label for="id_description">Descriptions </label>
                <input type="checkbox" name="description" id="id_description">
        </div>

    </div><!--end of row-->
    
    <hr />
    
    <div class="row"><!--start of row-->
        <div class="col-md-10">
        </div>
        <div class="col-md-2">
                <div class="btns">
                    <button class="btn btn-default" type="submit">Submit</button>
                    <button class="btn btn-default" type="reset" id="reset">Reset</button>
                </div>
        </div>
    </div><!--end of row-->
</form><!--end of form-->

    <div class="row" style="padding-top: 30px;"></div>

    <div class="row">
    <div class="col-md-12">
        <table id="myTable" class="display table" width="100%">
        <thead>
        <tr>
            {% if loc_display %}
            <th>Locations</th>
            {% endif %}
            {% if sub_display %}
            <th>Sublocations</th>
            {% endif %}
            {% if sec_display %}
            <th>Sectors</th>
            {% endif %}
            {% if imp_display %}
            <th>Implementers</th>
            {% endif %}
            <th>Project Name</th>
            <th>Funders</th>
            <th>Duration</th>
            <th>Value</th>
            <th>% Spent to Date</th>
        </tr>
        </thead>
    {% for obj in filtered %}
        <tr>

            {% if loc_display %}
            <td>
                {% for location in obj.locations %}
                {{ location }}{% if forloop.last %}{% else %}, {% endif %}
            {% endfor %}
            </td>
            {% endif %}

            {% if sub_display %}
            <td>
                {% for sublocation in obj.sublocations %}
                {{ sublocation }}{% if forloop.last %}{% else %}, {% endif %}
            {% endfor %}
            </td>
            {% endif %}

            {% if sec_display %}
            <td>
                {% for sector in obj.sectors %}
                {{ sector }}{% if forloop.last %}{% else %}, {% endif %}
            {% endfor %}
            </td>
            {% endif %}
            {% if imp_display %}
            <td>
                {% for implementer in obj.implementers.all %}
                {{ implementer }}{% if forloop.last %}{% else %}, {% endif %}
                {% endfor %}
            </td>
            {% endif %}

            <td>
                <a href={% url 'data-entry:project_details' obj.id %}>{{ obj.name }}</a>
                <p id="desc" style="display:none">{{ obj.description|truncatechars:300 }}</p>

            </td>
            <td>
            {% for funder in obj.funders.all %}
                {{ funder }}{% if forloop.last %}{% else %}, {% endif %}
            {% endfor %}

            </td>
            <td>{{ obj.duration }}</td>
            <td>{{ obj.value|intcomma }} {{ obj.currency.abbrev }}</td>
            <td>{{ obj.percentage_spent }}</td>
        </tr>
    {% endfor %}
    </table>
    </div>
    </div>
    </div>
</div>

</div><!-- end of fluid container -->

templates/reports/location_report.html
{% extends 'base.html' %}
{% load humanize %}
{% load report_extras %}
{% block title %} Location report {% endblock %}
{% block header_text%} Location Report {% endblock %}
{% block content %}
<div class="row" style="padding-top: 20px;"></div>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-4"></div>
        <div class="col-md-4" style="text-align: center;">
            <form method="get" action="">
                <div class="form-group">
                <label for="location">Location</label>

                {{ form.location }}
                </div>
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
<div class="row" style="padding-top: 30px;"></div>
    <div class="row">
    <div class="col-md-12">
        {% if projects %}
        <table id="myTable" class="display table table-condensed table-bordered" width="100%" style="font-size: 11px;
        line-height: 1">
        <caption>Projects in {{ location.name }} location.</caption>
        <thead>
        <tr>
            <th>Project Name</th>
            <th>Funders</th>
            <th>Implementers</th>
            <th>Duration</th>
            <th>Value</th>
            <th>% Spent to Date</th>
        </tr>
        </thead>
    {% for obj in filtered %}
        <tr>
            <td>
                <a href={% url 'data-entry:project_details' obj.id %}>{{ obj.name }}</a>
                <p id="desc" style="display:none">{{ obj.description|truncatechars:300 }}</p>

            </td>
            <td class="col-md-3">
            {% for funder in obj.funders.all %}
                {{ funder }}{% if forloop.last %}{% else %}, {% endif %}
            {% endfor %}

            </td>
            <td class="col-md-3">
            {% for implementer in obj.implementers.all %}
                {{ implementer }}{% if forloop.last %}{% else %}, {% endif %}
            {% endfor %}

            </td>
            <td>{{ obj.duration }}</td>
            <td>{{ obj.value|intcomma }} {{ obj.currency.abbrev }}</td>
            <td>{{ obj.percentage_spent }}</td>
        </tr>
    {% endfor %}
    </table>
    {% endif %}
    </div>
    </div>
<div class="row">
<div class="col-md-12">
<div class="col-md-2"></div>
<div class="col-md-8" style="text-align: center;">
    <div id="chart_div"></div>
</div>
<div class="col-md-2"></div>
</div>
</div>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
    {% if projects %}
    <script type="text/javascript">

      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');

        data.addRows([
          {% for key, value in allocation_dict.items %}
            ["{{ key|norm }}", {{ value }}],
          {% endfor %}
        ]);

        // Set chart options
        var title = "{{ location.name }}" + " location project funders"
        var options = {'title':title,
                       'width':600,
                       'height':500};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css">
    <script src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function(){
        $('#myTable').dataTable();

        });
    </script>
    {% endif %}
{% endblock %}