aims/urls.py
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from .views import *

urlpatterns = [
    url(r'login_success/$', login_success, name='login_success'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^management/', include('management.urls')),
    url(r'^data-entry/', include('data_entry.urls', namespace='data-entry')),
    url(r'^reports/', include('reports.urls', namespace='reports')),
    url(r'^project_list/', include('reports.urls', namespace='projects')),
    url(r'^help/', include('help.urls', namespace='help')),
    url(r'^', include('home.urls')),
    url(r'^', include('django.contrib.auth.urls')),
    #url(r'^$', 'aims.views.home', name='home'),


    url(r'^admin/', include(admin.site.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

data_entry/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    # url(r'^$', login_required(ProjectListView.as_view()), name='dashboard'),
    url(r'^$', login_required(ProjectListView), name='dashboard'),
    url(r'^project/create/$', login_required(ProjectCreateView.as_view()), name='project_add'),
    url(r'^project/update/(?P<pk>[^/]+)/$', login_required(ProjectUpdateView.as_view()), name='project_update'),
    url(r'^project/details/(?P<pk>[^/]+)/$', ProjectDetailView.as_view(), name='project_details'),
    url(r'^project/export/(?P<pk>[^/]+)/$', project_export, name='project_export'),
    url(r'^download/(?P<pk>[^/]+)/$', download_handler, name='download'),
    url(r'^project/delete/(?P<pk>[^/]+)/$', login_required(ProjectDelete.as_view()),
        name='project_delete'),
    #url(r'^sublocations/(?P<locationID>[^/]+)/', getSublocations, name='sublocations'),
    url(r'^sublocations/$', ajaxSublocations, name='ajax_sublocations'),
    url(r'^subpsgs/$', ajaxSubPSGs, name='ajax_subpsgs'),
]

data_entry/models.py
from django.db import models
from management.models import Organization, Currency, Location, Sector, SubLocation, SubPSG, PSG
import datetime
from datetime import timedelta
from calendar import monthrange
import uuid
from django.conf import settings


class UnsavedForeighKey(models.ForeignKey):
    allow_unsaved_instance_assignment = True


class Project(models.Model):
    """Projects receiving AID"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    name = models.TextField()
    description = models.TextField()
    lastModified = models.DateField(auto_now=True, blank=True, null=True)
    startDate = models.DateField(blank=True, null=True)
    endDate = models.DateField(blank=True, null=True)
    funders = models.ManyToManyField(Organization, related_name="funders")
    implementers = models.ManyToManyField(Organization, related_name="implementers")
    value = models.FloatField()
    currency = models.ForeignKey(Currency)
    rateToUSD = models.DecimalField(max_digits=6, decimal_places=2)
    active = models.BooleanField(default=True, blank=True)
    ocha_fts_reported = models.NullBooleanField(blank=True, null=True, choices=settings.BOOLEAN_CHOICES)
    sdrf_ssa = models.CharField(max_length=100, blank=True, null=True, choices=settings.SDRF_SSA_CHOICES)
    funding_instrument = models.CharField(max_length=100, blank=True, null=True, choices=settings.FUNDING_INSTRUMENTS)
    funding_channel = models.CharField(max_length=20, blank=True, null=True, choices=settings.FUNDING_CHANNELS)
    gender = models.CharField(max_length=20, blank=True, null=True, choices=settings.MULTIFIELD_CHOICES)
    capacity_building = models.CharField(max_length=20, blank=True, null=True, choices=settings.MULTIFIELD_CHOICES)
    stabilization = models.CharField(max_length=20, blank=True, null=True, choices=settings.MULTIFIELD_CHOICES)
    conflict_sensitivity_analysis = models.CharField(max_length=100, blank=True, null=True,
                                                     choices=settings.SENSITIVITY_ANALYSIS_CHOICES)
    conflict_sensitivity_monitoring = models.NullBooleanField(blank=True, null=True, choices=settings.BOOLEAN_CHOICES)

    class Meta:
        db_table = 'project'

    def __str__(self):
        return self.name

    def save(self):
        if datetime.date.today() > self.endDate.date():
            self.active = False
        else:
            pass
        super(Project, self).save()

    @property
    def duration(self):
        delta = 0
        while True:
            mdays = monthrange(self.startDate.year, self.startDate.month)[1]
            self.startDate += timedelta(days=mdays)
            if self.startDate <= self.endDate:
                delta += 1
            else:
                break
        out = "{0} months".format(delta)
        return out

    @property
    def percentage_spent(self):
        spending = Spending.objects.get(project=self).spendingToDate
        try:
            percentage = (spending / self.value) * 100
        except ZeroDivisionError:
            percentage = 0
        out = "{0:5.2f} %".format(percentage)
        return out

    @property
    def locations(self):
        l = LocationAllocation.objects.filter(project=self).values_list('location')
        f = Location.objects.filter(id__in=l).values_list('name')
        location_list = [' '.join(item) for item in f]
        return location_list

    @property
    def sublocations(self):
        l = LocationAllocation.objects.filter(project=self).values_list('sublocations')
        f = SubLocation.objects.filter(id__in=l).values_list('name')
        sublocation_list = [' '.join(item) for item in f]
        return sublocation_list

    @property
    def sectors(self):
        l = SectorAllocation.objects.filter(project=self).values_list('sector')
        f = Sector.objects.filter(id__in=l).values_list('name')
        sector_list = [' '.join(item) for item in f]
        return sector_list


class Spending(models.Model):
    """How a project's value has and is intended to been spent"""
    project = models.OneToOneField(Project)
    spendingToDate = models.FloatField(help_text="Total amount of aid spent up to date", blank=True, null=True)
    lastYearSpending = models.FloatField(help_text="Total amount of aid spent last year", blank=True, null=True)
    thisYearSpending = models.FloatField(help_text="Amount expected to be spent this year", blank=True)
    nextYearSpending = models.FloatField(help_text="Total amount of aid anticipated to be spent next year", blank=True,
                                         null=True)

    class Meta:
        db_table = 'project_spending'

    def __str__(self):
        return self.project.name


class Contact(models.Model):
    """Person who knows more about the Project"""
    project = models.OneToOneField(Project)
    name = models.CharField(max_length=100)
    organization = models.CharField(max_length=100, blank=True, null=True)
    number = models.CharField(max_length=50)
    email = models.EmailField()

    class Meta:
        db_table = 'project_contacts'

    def __str__(self):
        return self.name


class Document(models.Model):
    """Documents relevant to a project"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = UnsavedForeighKey(Project)
    file = models.FileField(upload_to=settings.DOCUMENT_UPLOAD_DIR, blank=True, null=True)
    name = models.CharField(max_length=150, blank=True, null=True)
    link_to_document_website = models.URLField(blank=True, null=True)

    class Meta:
        db_table = 'project_documents'

    def __str__(self):
        return "{0}".format(self.name)


class SectorAllocation(models.Model):
    """Amount of project's value spent in various sectors"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = UnsavedForeighKey(Project)
    sector = models.ForeignKey(Sector)
    allocatedPercentage = models.DecimalField(max_digits=4, decimal_places=1)

    class Meta:
        db_table = 'sector_allocations'

    def __str__(self):
        return "{0} - {1} - {2}".format(self.project.name, self.sector.name, self.allocatedPercentage)

    @property
    def percentage(self):
        precentage = "{0:5.2f} %".format(self.allocatedPercentage)
        return precentage


class LocationAllocation(models.Model):
    """Percentage of project's value spent in various locations"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = UnsavedForeighKey(Project)
    location = models.ForeignKey(Location)
    sublocations = models.ManyToManyField(SubLocation)
    allocatedPercentage = models.DecimalField(max_digits=4, decimal_places=1)

    class Meta:
        db_table = 'location_allocations'

    def __str__(self):
        return "{0} - {1} - {2}".format(self.project.name, self.location.name, self.allocatedPercentage)

    @property
    def percentage(self):
        precentage = "{0:5.2f} %".format(self.allocatedPercentage)
        return precentage


class UserOrganization(models.Model):
    """Organizations missing in organization list but involved in projects. User defined"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    project = UnsavedForeighKey(Project)
    name = models.CharField(max_length=200, help_text="Organization involved in project but not in existing list",
                            unique=True)
    role = models.CharField(max_length=12, choices=(('Funder', 'Funder'), ('Implementer', 'Implementer')),
                            help_text="Role of organization in project")

    class Meta:
        db_table = 'user_organisations'

    def __str__(self):
        return self.name


class SubPSGAllocation(models.Model):
    """Percentage of project's value allocated to various subPSGs"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = UnsavedForeighKey(Project)
    psg = models.ForeignKey(PSG)
    subpsg = models.ForeignKey(SubPSG)
    allocatedPercentage = models.DecimalField(max_digits=4, decimal_places=1)

    class Meta:
        db_table = 'subpsg_allocations'

    def __str__(self):
        return "{0} - {1} - {2}".format(self.project.name, self.subpsg.name, self.allocatedPercentage)

    @property
    def percentage(self):
        precentage = "{0:5.2f} %".format(self.allocatedPercentage)
        return precentage

data_entry/forms.py
from django.forms import ModelForm
from .models import Project, LocationAllocation, SectorAllocation, UserOrganization, Document, Spending, Contact, \
    SubPSGAllocation
from django.forms.models import BaseModelFormSet
from django.forms.models import inlineformset_factory


class ProjectForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['rows'] = '2'
        self.fields['description'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['rows'] = '3'
        self.fields['startDate'].widget.attrs['class'] = 'form-control'
        self.fields['endDate'].widget.attrs['class'] = 'form-control'
        self.fields['funders'].widget.attrs['class'] = 'form-control'
        self.fields['implementers'].widget.attrs['class'] = 'form-control'
        self.fields['value'].widget.attrs['class'] = 'form-control'
        self.fields['currency'].widget.attrs['class'] = 'form-control'
        self.fields['rateToUSD'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Project
        exclude = ('id', 'lastModified', 'user', 'active')


class BaseLocationAllocationFormSet(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super(BaseLocationAllocationFormSet, self).__init__(*args, **kwargs)
        self.queryset = LocationAllocation.objects.none()


class BaseSubPSGAllocationFormSet(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super(BaseSubPSGAllocationFormSet, self).__init__(*args, **kwargs)
        self.queryset = SubPSGAllocation.objects.none()


class BaseSectorAllocationFormSet(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super(BaseLocationAllocationFormSet, self).__init__(*args, **kwargs)
        self.queryset = SectorAllocation.objects.none()


class BaseDocumentFormSet(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super(BaseDocumentFormSet, self).__init__(*args, **kwargs)
        self.queryset = Document.objects.none()


class BaseUserOrganizationFormSet(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super(BaseUserOrganizationFormSet, self).__init__(*args, **kwargs)
        self.queryset = UserOrganization.objects.none()


class BaseContactFormSet(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        super(BaseContactFormSet, self).__init__(*args, **kwargs)
        self.queryset = Contact.objects.none()


class SectorAllocationForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SectorAllocationForm, self).__init__(*args, **kwargs)
        self.fields['sector'].widget.attrs['class'] = 'form-control'
        self.fields['allocatedPercentage'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = SectorAllocation
        exclude = ('id', 'project')


class LocationAllocationForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(LocationAllocationForm, self).__init__(*args, **kwargs)
        self.fields['location'].widget.attrs['class'] = 'form-control'
        self.fields['sublocations'].widget.attrs['class'] = 'form-control'
        self.fields['allocatedPercentage'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = LocationAllocation
        exclude = ('id', 'project')


class SubPSGAllocationForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SubPSGAllocationForm, self).__init__(*args, **kwargs)
        self.fields['psg'].widget.attrs['class'] = 'form-control'
        self.fields['subpsg'].widget.attrs['class'] = 'form-control'
        self.fields['allocatedPercentage'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = SubPSGAllocation
        exclude = ('id', 'project')


class UserOrganizationForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserOrganizationForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['role'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = UserOrganization
        exclude = ('id', 'project')


class DocumentForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['file'].widget.attrs['class'] = 'form-control'
        self.fields['link_to_document_website'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Document
        exclude = ('project', 'id')


class SpendingForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SpendingForm, self).__init__(*args, **kwargs)
        self.fields['spendingToDate'].widget.attrs['class'] = 'form-control'
        self.fields['nextYearSpending'].widget.attrs['class'] = 'form-control'
        self.fields['thisYearSpending'].widget.attrs['class'] = 'form-control'
        self.fields['lastYearSpending'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Spending
        exclude = ('project',)


class ContactForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['organization'].widget.attrs['class'] = 'form-control'
        self.fields['number'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Contact
        exclude = ('project',)


LocationAllocationFormset = inlineformset_factory(Project, LocationAllocation, fields=('location', 'sublocations',
                                                                                       'allocatedPercentage'),
                                                  can_delete=True, extra=1, form=LocationAllocationForm)

SubPSGAllocationFormset = inlineformset_factory(Project, SubPSGAllocation, fields=('psg', 'subpsg',
                                                                                   'allocatedPercentage'),
                                                can_delete=True, extra=1, form=SubPSGAllocationForm)

SectorAllocationFormset = inlineformset_factory(Project, SectorAllocation, fields=('sector', 'allocatedPercentage'),
                                                can_delete=True, extra=1, form=SectorAllocationForm)

UserOrganizationFormset = inlineformset_factory(Project, UserOrganization, fields=('name', 'role'),
                                                can_delete=True, extra=1, form=UserOrganizationForm)

DocumentFormset = inlineformset_factory(Project, Document, fields=('name', 'file', 'link_to_document_website'),
                                        can_delete=True, extra=1,
                                        form=DocumentForm)

templates/data_entry/index.html
{% extends "base.html" %}
{% load humanize %}
{% block title %} Data Entry {% endblock %}

{% block header_text%} Data Entry {% endblock %}

{% block content %}
<div class="container">

    <div class="row" style="padding-top: 20px;"></div>
    <div id="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <a href="{% url 'data-entry:project_add' %}"><h4 style="text-align: center;">Add new project</h4></a>
                </div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </div>

        <div class="row" style="padding-top: 60px;"></div>
    <div class="row">
    <div>
        <div class="col-md-2">
            <form action="" method="get">
                <label for="funders__icontains">Funders</label>
                <div class="form-group">

                    {{ filtered.form.funders__icontains }}
                </div>
                <label for="implementers__icontains">Implementers</label>
                <div class="form-group">
                    {{ filtered.form.implementers__icontains }}
                </div>
                <input class="form-control" id="id_name__icontains" name="name__icontains" type="text" placeholder="project name">
                <br>
                <div class="btns">
                    <button type="submit">Submit</button>
                    <button type="reset" id="reset">Reset</button>
                </div>
            </div>
            <div class="col-md-2">
                <input class="form-control" id="id_startDate" name="startDate" type="text" placeholder="start date">
                <input class="form-control" id="id_endDate" name="endDate" type="text" placeholder="end date">
                <br>
                <label for="id_myProjects">My projects</label>
                <input id="id_myProjects" type="checkbox" name="myProjects" placeholder="show my projects">

            </div>
            </form>
        <div class="row" style="padding-bottom: 20px;"></div>
    </div>

    <div class="col-md-12">
    <div style="float: right;">
        <label for="id_description">Show descriptions</label>
        <input type="checkbox" name="description" id="id_description">
    </div>
        <table id="myTable" class="display table table-bordered" width="100%">
        <thead>
        <tr>
            {% if loc_display %}
            <th>Locations</th>
            {% endif %}
            {% if sub_display %}
            <th>Sublocations</th>
            {% endif %}
            {% if sec_display %}
            <th>Sectors</th>
            {% endif %}
            <th>Project Name</th>
            <th>Funders</th>
            <th>Implementers</th>
            <th>Start date</th>
            <th>End date</th>
            <th>Value in original currency</th>
            <th>Original currency</th>
        </tr>
        </thead>
    {% for obj in filtered %}
        <tr>
            <td class="col-md-3">
                <a href={% url 'data-entry:project_update' obj.id %}>{{ obj.name }}</a>
                <p id="desc" style="display:none">{{ obj.description|truncatechars:300 }}</p>

            </td>
            <td class="col-md-2">
            {% for funder in obj.funders.all %}
                {{ funder }}{% if forloop.last %}{% else %}, {% endif %}
            {% endfor %}

            </td>
            <td class="col-md-2">
            {% for implementer in obj.implementers.all %}
                {{ implementer }}{% if forloop.last %}{% else %}, {% endif %}
            {% endfor %}

            </td>
            <td>{{ obj.startDate }}</td>
            <td>{{ obj.endDate }}</td>
            <td class="col-md-1">{{ obj.value|intcomma }}</td>
            <td class="col-md-1">{{ obj.currency }}</td>
        </tr>
    {% endfor %}
    </table>
    </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#id_description').click(function () {
            if ($("#id_description").is(':checked'))
                $('td p').show();  // checked
            else
                $('td p').hide();
        });
    });
    </script>
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css">
    <script src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function(){
        $('#myTable').dataTable();

        });
    </script>
 <script>
        $(document).ready(function() {
            $('option', $('#id_funders__icontains')).each(function (element) {
                    $(this).removeAttr('selected').prop('selected', false);
                });
                $('option', $('#id_implementers__icontains')).each(function (element) {
                    $(this).removeAttr('selected').prop('selected', false);
                });
                $('#id_funders__icontains').multiselect('refresh');
                $('#id_implementers__icontains').multiselect('refresh');
            $('#reset').on('click', function () {
                $('option', $('#id_funders__icontains')).each(function (element) {
                    $(this).removeAttr('selected').prop('selected', false);
                });
                $('option', $('#id_implementers__icontains')).each(function (element) {
                    $(this).removeAttr('selected').prop('selected', false);
                });
                $('#id_funders__icontains').multiselect('refresh');
                $('#id_implementers__icontains').multiselect('refresh');
            });

        });
    </script>
{% endblock %}

templates/data_entry/project_confirm_delete.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete the project <b>"{{ object.name }}"</b>?</p>
    <input type="submit" value="Confirm" />
</form>
</body>
</html>

templates/data_entry/project_details.html
{% extends "base.html" %}
{% load humanize %}
{% load filetransfers %}
{% block title %} Project Details {% endblock %}

{% block header_text%} Project Details {% endblock %}

{% block content %}

<style>

  .some-space-top{
      padding-top: 40px;
  }
  .thirty-px-padding-top{
    padding-top: 30px;
  }

</style>

<div class="fluid-container"><!--Star of Wrapper-->
<div class="row some-space-top"><!-- start of row -->
        
        <h3 class="">Project Name: {{ project.name }}</h3> <hr />
        
        <div class="row"><!-- start of row -->
            
            <div class="col-md-6">
              <br />
              <p><b>Desciption: </b> {{ project.description }}</p>
            </div>

            <div class="col-md-2">
              <h4>Project Duration</h4>
              <p><b>Start Date: </b> {{ project.startDate }}</p>
              <p><b>End Date: </b> {{ project.endDate }}</p>
            </div>

            <div class="col-md-2">
              <h4>Project value</h4>
              <p>{{ project.value|intcomma }} {{ project.currency }}</p>

              <h4>Funders</h4>
              {% for funder in project.funders.all %}
                    <p>{{ funder.name }}</p>
              {% endfor %}
              {% for org in other_organizations %}
                  {% if org.role == "Funder" %}
                      <p>org.name</p>
                  {% endif %}
              {% endfor %}
            </div>

            <div class="col-md-2">
              <h4>Implementers</h4>
              {% for implementer in project.implementers.all %}
                    <p>{{ implementer.name }}</p>
              {% endfor %}
              {% for org in other_organizations %}
                  {% if org.role == "Implementer" %}
                    <p>{{ org.name }}</p>
                  {% endif %}
              {% endfor %}           
            
              <h4>Sectors and allocations</h4>
              {% for sector in sec_allocations %}
                  <p>{{ sector.sector.name }} - {{ sector.percentage }}</p>
              {% endfor %}
            </div>

        </div><!-- end of row -->

        <div class="row"><!-- start of row -->
          
          <div class="col-md-8"><!-- start of col-md-9 -->
            <div class="row"> <!-- start of row -->

                    <h3>Locations And Respective Allocations</h3> <hr />

                    <div class="col-md-6">
                      {% for location in loc_allocations %}
                          <h4>{{ location.location.name }} - {{ location.percentage }}</h4>
                          <span>Sublocations involved</span>
                          <ol>
                          {% for sublocation in location.sublocations.all %}
                              <li>{{ sublocation.name }}</li>
                          {% endfor %}
                          </ol>
                      {% endfor %}
                    </div>

                    <div class="col-md-6">
                      <h4>Sub-PSGs And Respective allocations</h4>
                      {% if subpsg_allocations %}
                      {% for subpsg in subpsg_allocations %}
                          <p>{{ subpsg.subpsg.name }} - {{ subpsg.percentage }}</p>
                      {% endfor %}
                      {% else %}
                          <span>No data available</span>
                      {% endif %}
                      {% if documents %}
                    </div>
            </div><!-- end of row -->
          </div><!--end of col-md-9-->

          <div class="col-md-1"></div>

          <div class="col-md-3"><!-- start of col-md-3 -->

              <h3>Projects</h3> <hr />
              {% for document in documents %}
                    <p>{{ document.name }}
                        <a href="{% url 'data-entry:download' pk=document.id %}">Download</a>
                    </p>
                    <p>Link to project document:</p>
                    <p>{{ document.link_to_document_website }}</p>
                {% endfor %}
                {% endif %}
          </div><!-- end of col-md-3 -->

        </div><!-- end of row -->


        <div class="row"><!-- start of row -->

            <hr />
            <div class="col-md-10"></div>
            <div class="col-md-2">
                  <div class="pull-right">
                      <a href="{% url 'reports:dashboard'%}"><button class="btn btn-default btn-large">Go back</button></a>
                   </div>
            </div>

        </div><!-- end of row-->

        <div class="row thirty-px-padding-top">
          <div id="map-canvas"></div>
        </div>

</div><!--end of row -->
</div><!--End Of Wrapper-->

<script>
function initialize() {
  country = new google.maps.LatLng(5.134736, 46.186371)
  var mapOptions = {
    zoom: 5,
    center: country
  };

  var map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);
  var markers = [
        {% for allocation in loc_allocations %}
        ['{{ allocation.project }}', '{{ allocation.location.lat }}',
            '{{ allocation.location.lng }}', '{{ allocation.location.name }}'],
        {% endfor %}
    ];
  console.log(markers);
  for( i = 0; i < markers.length; i++ ) {
      var infoWindow = new google.maps.InfoWindow(), marker, i;
      var position = new google.maps.LatLng(markers[i][1], markers[i][2]);
      marker = new google.maps.Marker({
            position: position,
            map: map,
            title: markers[i][0]
        });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
                var content = "<p>" + markers[i][3] + "</p>" + "<p>" + markers[i][0] + "</p>"
                infoWindow.setContent(content);
                infoWindow.open(map, marker);
            }
        })(marker, i));
  }
 var subs = [
 {% for allocation in loc_allocations %}
     {% for sub in allocation.sublocations.all %}
        ['{{ allocation.project }}', '{{ allocation.location.name }}', '{{ sub.name }}', '{{ sub.lat }}',
            '{{ sub.lng }}'],
        {% endfor %}
 {% endfor %}
 ];

for( i = 0; i < subs.length; i++ ) {
      var infoWindow = new google.maps.InfoWindow(), marker, i;
      var position = new google.maps.LatLng(subs[i][3], subs[i][4]);
      marker = new google.maps.Marker({
            position: position,
            map: map,
            title: subs[i][0]
        });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
                var content = "<p>" + subs[i][2] + " - " + subs[i][1] + "</p>" + "<p>" + subs[i][0] + "</p>"
                infoWindow.setContent(content);
                infoWindow.open(map, marker);
            }
        })(marker, i));
  }
console.log(subs)
}

function loadScript() {
  var script = document.createElement('script');
  script.type = 'text/javascript';
  script.src = 'https://maps.googleapis.com/maps/api/js?v=3.exp' +
      '&signed_in=false&callback=initialize';
  document.body.appendChild(script);
}

window.onload = loadScript;
</script>

{% endblock %}